name = "m&a create cf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "188aa0ad3a10d4c25dcdaa64493a8566d4d5a4ec6786865d67e8cd8fa5884cca"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
