name = "m&a create cf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c64a7f38442da2333445a2f7f5ac3843ef8b583821e61cc11b1ee9712030c6b8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
