name = "m&a create cf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f7dc7f61dcb828296b269a8b15694f34510f1d6aeaaa959ae519911778b019a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
